INSERT INTO candidates (name, experience, skills) VALUES
('Carla Zieme', 2, 'Production Planning, Waste Management, Crisis Handling'),
('Miss Natasha Funk', 7, 'Team Leadership, Safety Compliance, Crisis Handling'),
('Ernesto Macejkovic', 4, 'Safety Compliance, Waste Management, Team Leadership'),
('Andres Schumm PhD', 15, 'Crisis Handling, Production Planning, Sustainability'),
('Daryl Stanton', 14, 'Safety Compliance, Team Leadership, Waste Management'),
('Beulah Bruen Sr.', 6, 'Crisis Handling, Team Leadership, Waste Management'),
('Rodney Quigley MD', 11, 'Crisis Handling, Production Planning, Team Leadership'),
('Cathy Grant', 3, 'Production Planning, Sustainability, Waste Management'),
('Viola Cormier', 10, 'Waste Management, Safety Compliance, Sustainability'),
('Caleb Walter IV', 5, 'Waste Management, Production Planning, Team Leadership'),
('Simon Smith', 6, 'Waste Management, Sustainability, Crisis Handling'),
('Edgar Keeling', 10, 'Production Planning, Crisis Handling, Safety Compliance'),
('Carroll Mills', 1, 'Waste Management, Sustainability, Safety Compliance'),
('Al Moore', 10, 'Waste Management, Crisis Handling, Safety Compliance'),
('Lamar Brown', 14, 'Waste Management, Production Planning, Safety Compliance'),
('Johnnie Konopelski DVM', 3, 'Safety Compliance, Team Leadership, Sustainability'),
('Olga McDermott', 1, 'Sustainability, Team Leadership, Waste Management'),
('Karen Heaney-Lehner', 13, 'Production Planning, Crisis Handling, Sustainability'),
('Claire O'Connell', 2, 'Sustainability, Crisis Handling, Waste Management'),
('Brett Schroeder', 10, 'Sustainability, Production Planning, Waste Management'),
('Holly Senger', 6, 'Production Planning, Waste Management, Team Leadership'),
('Melvin Schmitt', 4, 'Crisis Handling, Production Planning, Team Leadership'),
('Mr. Emilio Haley', 14, 'Waste Management, Safety Compliance, Sustainability'),
('Taylor Hickle', 8, 'Waste Management, Safety Compliance, Crisis Handling'),
('Mr. Sherman Smitham-Johnson', 15, 'Team Leadership, Production Planning, Safety Compliance'),
('Leticia Lindgren', 2, 'Waste Management, Safety Compliance, Crisis Handling'),
('Claudia Heidenreich', 7, 'Crisis Handling, Sustainability, Waste Management'),
('Sonia Franecki', 2, 'Production Planning, Team Leadership, Waste Management'),
('Miriam Orn', 8, 'Team Leadership, Safety Compliance, Production Planning'),
('Mr. Sherman Franey', 12, 'Crisis Handling, Safety Compliance, Sustainability'),
('Teri Nader', 9, 'Crisis Handling, Team Leadership, Waste Management'),
('Deanna Smitham', 14, 'Sustainability, Waste Management, Safety Compliance'),
('May Jaskolski', 11, 'Production Planning, Sustainability, Safety Compliance'),
('Forrest Collins', 12, 'Waste Management, Team Leadership, Safety Compliance'),
('Ruby Berge', 8, 'Waste Management, Crisis Handling, Sustainability'),
('Ollie Parisian', 2, 'Safety Compliance, Production Planning, Waste Management'),
('Louis Russel', 7, 'Waste Management, Safety Compliance, Team Leadership'),
('Joshua Runolfsdottir', 12, 'Sustainability, Safety Compliance, Production Planning'),
('Toby Torphy-Moore', 4, 'Waste Management, Crisis Handling, Safety Compliance'),
('Mark Thiel', 5, 'Crisis Handling, Waste Management, Team Leadership');
